// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package flygraphqlclient

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// GetAppExtrasApp includes the requested fields of the GraphQL type App.
type GetAppExtrasApp struct {
	SharedIpAddress string                                 `json:"sharedIpAddress"`
	Hostname        string                                 `json:"hostname"`
	Regions         []GetAppExtrasAppRegionsRegion         `json:"regions"`
	Volumes         GetAppExtrasAppVolumesVolumeConnection `json:"volumes"`
}

// GetSharedIpAddress returns GetAppExtrasApp.SharedIpAddress, and is useful for accessing the field via an interface.
func (v *GetAppExtrasApp) GetSharedIpAddress() string { return v.SharedIpAddress }

// GetHostname returns GetAppExtrasApp.Hostname, and is useful for accessing the field via an interface.
func (v *GetAppExtrasApp) GetHostname() string { return v.Hostname }

// GetRegions returns GetAppExtrasApp.Regions, and is useful for accessing the field via an interface.
func (v *GetAppExtrasApp) GetRegions() []GetAppExtrasAppRegionsRegion { return v.Regions }

// GetVolumes returns GetAppExtrasApp.Volumes, and is useful for accessing the field via an interface.
func (v *GetAppExtrasApp) GetVolumes() GetAppExtrasAppVolumesVolumeConnection { return v.Volumes }

// GetAppExtrasAppRegionsRegion includes the requested fields of the GraphQL type Region.
type GetAppExtrasAppRegionsRegion struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// GetCode returns GetAppExtrasAppRegionsRegion.Code, and is useful for accessing the field via an interface.
func (v *GetAppExtrasAppRegionsRegion) GetCode() string { return v.Code }

// GetName returns GetAppExtrasAppRegionsRegion.Name, and is useful for accessing the field via an interface.
func (v *GetAppExtrasAppRegionsRegion) GetName() string { return v.Name }

// GetAppExtrasAppVolumesVolumeConnection includes the requested fields of the GraphQL type VolumeConnection.
type GetAppExtrasAppVolumesVolumeConnection struct {
	Nodes []GetAppExtrasAppVolumesVolumeConnectionNodesVolume `json:"nodes"`
}

// GetNodes returns GetAppExtrasAppVolumesVolumeConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetAppExtrasAppVolumesVolumeConnection) GetNodes() []GetAppExtrasAppVolumesVolumeConnectionNodesVolume {
	return v.Nodes
}

// GetAppExtrasAppVolumesVolumeConnectionNodesVolume includes the requested fields of the GraphQL type Volume.
type GetAppExtrasAppVolumesVolumeConnectionNodesVolume struct {
	Name            string                                                           `json:"name"`
	Id              string                                                           `json:"id"`
	Region          string                                                           `json:"region"`
	SizeGb          int                                                              `json:"sizeGb"`
	AttachedMachine GetAppExtrasAppVolumesVolumeConnectionNodesVolumeAttachedMachine `json:"attachedMachine"`
}

// GetName returns GetAppExtrasAppVolumesVolumeConnectionNodesVolume.Name, and is useful for accessing the field via an interface.
func (v *GetAppExtrasAppVolumesVolumeConnectionNodesVolume) GetName() string { return v.Name }

// GetId returns GetAppExtrasAppVolumesVolumeConnectionNodesVolume.Id, and is useful for accessing the field via an interface.
func (v *GetAppExtrasAppVolumesVolumeConnectionNodesVolume) GetId() string { return v.Id }

// GetRegion returns GetAppExtrasAppVolumesVolumeConnectionNodesVolume.Region, and is useful for accessing the field via an interface.
func (v *GetAppExtrasAppVolumesVolumeConnectionNodesVolume) GetRegion() string { return v.Region }

// GetSizeGb returns GetAppExtrasAppVolumesVolumeConnectionNodesVolume.SizeGb, and is useful for accessing the field via an interface.
func (v *GetAppExtrasAppVolumesVolumeConnectionNodesVolume) GetSizeGb() int { return v.SizeGb }

// GetAttachedMachine returns GetAppExtrasAppVolumesVolumeConnectionNodesVolume.AttachedMachine, and is useful for accessing the field via an interface.
func (v *GetAppExtrasAppVolumesVolumeConnectionNodesVolume) GetAttachedMachine() GetAppExtrasAppVolumesVolumeConnectionNodesVolumeAttachedMachine {
	return v.AttachedMachine
}

// GetAppExtrasAppVolumesVolumeConnectionNodesVolumeAttachedMachine includes the requested fields of the GraphQL type Machine.
type GetAppExtrasAppVolumesVolumeConnectionNodesVolumeAttachedMachine struct {
	Id string `json:"id"`
}

// GetId returns GetAppExtrasAppVolumesVolumeConnectionNodesVolumeAttachedMachine.Id, and is useful for accessing the field via an interface.
func (v *GetAppExtrasAppVolumesVolumeConnectionNodesVolumeAttachedMachine) GetId() string {
	return v.Id
}

// GetAppExtrasResponse is returned by GetAppExtras on success.
type GetAppExtrasResponse struct {
	App GetAppExtrasApp `json:"app"`
}

// GetApp returns GetAppExtrasResponse.App, and is useful for accessing the field via an interface.
func (v *GetAppExtrasResponse) GetApp() GetAppExtrasApp { return v.App }

// __GetAppExtrasInput is used internally by genqlient
type __GetAppExtrasInput struct {
	AppId string `json:"appId"`
}

// GetAppId returns __GetAppExtrasInput.AppId, and is useful for accessing the field via an interface.
func (v *__GetAppExtrasInput) GetAppId() string { return v.AppId }

// The query or mutation executed by GetAppExtras.
const GetAppExtras_Operation = `
query GetAppExtras ($appId: String!) {
	app(name: $appId) {
		sharedIpAddress
		hostname
		regions {
			code
			name
		}
		volumes {
			nodes {
				name
				id
				region
				sizeGb
				attachedMachine {
					id
				}
			}
		}
	}
}
`

func GetAppExtras(
	ctx context.Context,
	client graphql.Client,
	appId string,
) (*GetAppExtrasResponse, error) {
	req := &graphql.Request{
		OpName: "GetAppExtras",
		Query:  GetAppExtras_Operation,
		Variables: &__GetAppExtrasInput{
			AppId: appId,
		},
	}
	var err error

	var data GetAppExtrasResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
